name: Nick McLarnan
markdown: kramdown
pygments: true

gallery:
  # path to the gallery
  dir: portfolio
  # title for gallery index
  title: "Portfolio"
  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: "Portfolio: "
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "date_time"
  # sizes for thumbnails
  thumbnail_size:
    x: 400
    y: 400

  # custom configuration for individual gallery
  # best_image is image for the index page (defaults to last image)
  galleries:
      breath:
